### ISSUE TITLE
Przewijanie strony (scroll)

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#1]
Okropnie powoli przesuwa się u mnie strona internetowa. Korzystam z Firefox i nie wiem czy to ma cokolwiek wspólnego z tym problemem. Dobrze byłoby ustawić szybsze przewijanie strony, bo dla zwiększenia czytelności zawiera niewiele treści i trzeba mocno scrollować, żeby zobaczyć co jest dalej.

**Comment by dbetka** [comment]
Trochę podciągnąłem prędkość scrollbara, jednak nic więcej już nie zrobię bo wtedy na chromie jeździ jak szalony. @arbuz93

**Comment by dbetka** [comment]
@arbuz93 Zamknij jak jest spoko

**Comment by arbuz93** [comment]
Zamykam.
