### ISSUE TITLE
Wyszukiwarka - strony produktów

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#10]
#### O co chodzi:

Potrzebne jest dodatkowe pole do wyszukiwarki w którym będzie podana domyślna ilość produktów na stronie i która będzie przesyłana wraz z wyszukiwaną frazą. 

Po za tym trzeba też zrobić możliwość wyświetlania odpowiedniej strony z produktami.

**Comment by arbuz93** [comment]
Powinniśmy najpierw uzupełnić trochę BD, bo inaczej nie będzie możliwości sprawdzenia, czy wszystko napewno działa po naszej myśli. @Drego31

**Comment by dbetka** [comment]
Nie tylko! Powinniśmy także oznaczać, którego wątku tyczą się nasze commity o czym zapomnieliśmy :P 
@arbuz93

**Comment by arbuz93** [comment]
Produktów mamy już wystarczającą ilość do testowania, więc dzisiaj zabawię się z filtrem zarządzającym wyświetlaniem odpowiedniej ilości produktów na jednej stronie.

**Comment by dbetka** [comment]
Powiedz jak go używać @arbuz93
