### ISSUE TITLE
SEO - metatagi

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#11]
#### Co zrobić:

Trzeba wykonać metatagi by roboty google'a mogły nas łatwo pozycjonować.

**Comment by arbuz93** [comment]
Miałem dla tych metatagów zrobić miejsce w BD. Jakie informacje mam przetrzymywać? @Drego31

**Comment by dbetka** [comment]
Dla każdej zakładki i dla każdego produktu by się przydało parę pól w BD o tym
Dokładnie sprecyzuję później bo muszę jeszcze to dobrze przygotować. 
@arbuz93

**Comment by arbuz93** [comment]
Jeżeli to wszystko, co mamy do zrobienia z nimi, to tylko test i zamykamy. @Drego31
