### ISSUE TITLE
Zmiana koloru lupy

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#13]
Potrzebuję lupę o kolorze pomarańczowym (kolor jak na stronie).

[Tutaj jest plik](https://www.dropbox.com/s/3oa00rf267w8lxk/lupa.png?dl=0)
A tu [link do strony](http://asbhp.arbuz.team/) byś kolorki sobie wziął.

@Erystyczny

**Comment by Erystyczny** [comment]
### Duża

> https://www.dropbox.com/s/k644mq324vnu9jn/lupa_p.png?dl=0

### Mniejsza

> https://www.dropbox.com/s/0r1eu28unl75idi/lupa_m_p.png?dl=0

**Comment by dbetka** [comment]
Tak to teraz wygląda:

![screenshot_20160607_225358](https://cloud.githubusercontent.com/assets/6503362/15874300/d3853258-2d02-11e6-8b3b-eac1d8a4edc1.png)

![screenshot_20160607_225419](https://cloud.githubusercontent.com/assets/6503362/15874305/d978a442-2d02-11e6-8b5b-90b08e751bd1.png)

Co sądzisz @Erystyczny ?

**Comment by Erystyczny** [comment]
Wygląda dobrze ale od razu podświetla się całe, fajnie by było żeby była lupa i po koiknięciu na nią pole wyszukiwania rozsunęło się w bok i było jaśniejszym szarym:
![_20160607_230304](https://cloud.githubusercontent.com/assets/19621505/15874581/1950c63e-2d04-11e6-84da-7575c4c515be.JPG)

**Comment by dbetka** [comment]
@Erystyczny Też o tym myślałem ale ostatecznie decyzja została podjęta o tym, że zamiast pola wyszukiwarki będzie tylko guzik w postaci lupy.

**Comment by dbetka** [comment]
Końcowy wygląd:

![screenshot_20160608_004946](https://cloud.githubusercontent.com/assets/6503362/15877224/f06ee2be-2d12-11e6-9717-3fc3f43ff558.png)
