### ISSUE TITLE
Rzeczy do zrobienia na prezentację strony w czwartek.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#14]
### 1. Wizualne upiększanie - strona startowa:
- Wrzucić grafikę tego motto: @Drego31 @Erystyczny 
- Zwężający się nagłówek: @Drego31 
- Ikonka powrotu na początek strony: @Drego31 
- Zróżnicowanie przejść na stronie startowej (mam na myśli jakieś akcenty lub całe bloki innym kolorze niż dwa dominujące kolory na stronie): @Drego31 
- Może dodamy ikonki do portali społecznościowych, nie ważne że nie będą działały: @Drego31 @Erystyczny 
### 2. Porządki w serwerowni - funkcje strony:
- Usunięcie wszystkich błędów i niedomówień związanych z funkcjonowaniem wyszukiwarki: @arbuz93 @Drego31 
- Filtry, czyli próba zapanowania nad biegunką bazy danych. @arbuz93  @Drego31  
- Wybieranie typu, dziedziny i rodzaju powinno być przedstawione za pomocą strzałek jak na zdjęciu poniżej: @arbuz93  @Drego31  @Erystyczny   ![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-07_20-13-53.png)   
- Do powyższego punktu dodałbym jeszcze wyświetlanie w selectach tylko tych opcji, które zawierają produkty (np. selekcja poprzez wyszukiwarkę): @arbuz93  @Drego31 
### Taka mała sprawa w związku z filtrami. Naprawdę dobrze wyglądałyby, gdybyśmy się wzorowali na zdjęciu poniżej: ![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-07_20-29-40.png)

W filtrach powinny znajdować się takie opcje jak: firma, kolor, certyfikaty, zagrożenia, zawody, oraz wyszukiwarka. Tak wyszukiwarka. Uważam, że powinna tam się znajdować wyszukiwarka, bo tyczy się ona tylko i wyłącznie produktów. Ikonka wyszukiwarki na panelu nagłówkowym, powinna po naciśnięciu, powinna przenosić właśnie do filtrów, gdzie zostałaby automatycznie wybrana wyszukiwarka. Więc w skrócie: pozbywamy się wyszukiwarki z nagłówka, ale pozostawiamy tam ikonkę lupy, która będzie przenosić użytkownika do wyszukiwarki w filtrach w zakładce 'Oferta'. @Drego31 @arbuz93 @Erystyczny

**Comment by arbuz93** [comment]
Wrzuciłbym jeszcze te wszystkie filtry w blok taki jak powinniśmy zrobić na stronie startowej. Poglądowo poniżej: @Drego31 
![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-07_21-22-41.png)

**Comment by dbetka** [comment]
To się zdecydujmy z tą wyszukiwarką xD 

Reszta wyjdzie w praniu ale nie wiem czy zdążymy :P

@arbuz93
