### ISSUE TITLE
Komunikaty o błędach z wyszukiwarki.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#19]
### To coś co próbuje się przebić pod wyszukiwarką to komunikaty formularza wyszukiwarki. Jest to jeden błąd, ale może pojawić się ich kilka jednocześnie. Można wyciągać je pętlą w HTMLu w taki sposób:

`{% for e in wyszukiwarka.zapytanie.errors %}`
`{{ e }}`
`{% endfor %}`

![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-08_16-36-54.png)

**Comment by dbetka** [comment]
Naprawione!
