### ISSUE TITLE
Przygotuj logo AS BHP

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#2]
Zrób duże i ładne z cieniem.
@Erystyczny 

![Alt Text](http://static.commentcamarche.net/es.ccm.net/pictures/Ud6krzOUaQiVrbx4IWkuzUrMD8vWr4qbG1wMtmWKQ94r7Doi6fybXXnACJoLFtKR-lol.png)

**Comment by Erystyczny** [comment]
#### AS BHP! :+1:

> `nazwa_N.png`
> N - skrótowo oznaczam jakieś szczegóły zdjęcia:
> S - małe
> C - z cieniem (w przypadku tej karty)

@Drego31 

**Napis** jest inną czcionką - tamtej nie znalazłem. jest w wersjach ze słowami osobno i słowami razem (jak Ci wygodniej)
- Razem:
  https://www.dropbox.com/s/w0u3e6tduigyk42/ODZIERZ%20ROBOCZA_S.png?dl=0
- Osobno:
  https://www.dropbox.com/s/tjz9mynqis3ymku/ODZIE%C5%BB_S.png?dl=0
  https://www.dropbox.com/s/w841buqrul57aqx/ROBOCZA_S.png?dl=0

**AS**:
https://www.dropbox.com/s/3tahbipqvsw7zbq/AS_C%2CS.png?dl=0

Podgląd w dużej rozdzielczości:
![as logo](https://cloud.githubusercontent.com/assets/19621505/15627566/49914fd6-24e8-11e6-9537-b6d76bb32cb9.jpg)

**Comment by dbetka** [comment]
Ortografia chłopie xD

![screenshot_20160528_170255](https://cloud.githubusercontent.com/assets/6503362/15628028/20eb6dec-24f6-11e6-828d-aa2e2c5b6635.png)
- @arbuz93 Co o tym sądzisz?
- @Erystyczny Masz poniżej widok w praktyce ;) 

![screenshot_20160528_173655](https://cloud.githubusercontent.com/assets/6503362/15628165/e3a66e46-24fa-11e6-9f3a-c0603043650c.png)

**Comment by Erystyczny** [comment]
Oj literówka w nazwie :p. Ważne że w projekcie się wszystko zgadza.
@Drego31

**Comment by arbuz93** [comment]
Dla mnie jest ok. @Drego31

**Comment by dbetka** [comment]
No to super! 
Dzięki @Erystyczny
