### ISSUE TITLE
Strzałki dla zakładki 'Oferta'.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#21]
### Mam dla ciebie zadanie kolego :smile:

Potrzebujemy podłużne, wypełnione strzałki w dwóch kolorach: pomarańczowym i jakimś szarym. Pomysł jest ogólnie taki. Możesz dodać coś od siebie ale tak, żeby sens został taki sam: 
![dropbox](https://camo.githubusercontent.com/3fa096ea6ec84598ab75f8a401b160b9e13d3bb2/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f383239373735342f73637265656e73686f74732f50727a656368777963656e69652532306f6272617a75253230656b72616e755f323031362d30362d30375f32302d31332d35332e706e67)

**Comment by Erystyczny** [comment]
jedną strzałke bez tekstu w kilku wersjach? czy ma być kilka?
@arbuz93

**Comment by arbuz93** [comment]
Jedna strzałka wystarczy w kilku kolorach. Napisy sami zrobimy.
@Erystyczny

**Comment by Erystyczny** [comment]
https://www.dropbox.com/sh/kf074oigmj19xfc/AAC9D88qJUSeWwBmefdLGGqUa?dl=0

**Comment by dbetka** [comment]
Wróciłem! ;) @Erystyczny 
Strzałkę poproszę o rozmiarach 300x50

**Comment by dbetka** [comment]
Zrób strzałeczkę i to będzie wszystko na dzisiaj @Erystyczny

**Comment by Erystyczny** [comment]
https://www.dropbox.com/sh/kf074oigmj19xfc/AAC9D88qJUSeWwBmefdLGGqUa?dl=0
z(1), z(2)
@arbuz93 @Drego31

**Comment by dbetka** [comment]
Piękne! Aktualnie to wszystko - Dzięki!

**Comment by dbetka** [comment]
Dodam je jeszcze tutaj przed zamknięciem wątku

**Comment by dbetka** [comment]
@Erystyczny Trzeba zmienić kolor pomarańczowej strzałki na [#ff7000](http://www.color-hex.com/color/ff7000)

**Comment by dbetka** [comment]
Do poprawki kolor pomarańczowy! (komentarz wyżej)

Tutaj jest pokazany przykład działania → [URL](https://www.dropbox.com/s/pjnckjai5rfdouh/vokoscreen-2016-06-12_23-22-56.mkv?dl=0)

Oraz zdjęcie ↓↓↓

![screenshot_20160612_232708](https://cloud.githubusercontent.com/assets/6503362/15993927/33e2ea6e-30f5-11e6-919e-cfc1ae0c323d.png)

@arbuz93 @Erystyczny
