### ISSUE TITLE
Ikonki do portali społecznościowych.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#22]
### Potrzebujemy ikonek.

Fajnie byłoby, gdyby były w kolorach strony, czyli FB zamiast biało-niebiski byłby szaro-pomarańczowy. Podobnie z resztą ikonek. Tym razem nie mam dla ciebie obrazków :smile:.

**Comment by Erystyczny** [comment]
jaka rozdziałka na ikone?
@arbuz93

**Comment by arbuz93** [comment]
Ekhm… Nie rozumiem pytania xD. Co znaczy rozdziałka?
@Erystyczny

**Comment by Erystyczny** [comment]
32x32? pixele

**Comment by arbuz93** [comment]
Aaa… Rozmiar grafiki. Dwie rozdziałki poproszę: 64x64 i 32x32. :smile: 
@Erystyczny

**Comment by Erystyczny** [comment]
już robie w 32, za duzo roboty jak ma byc na juz

**Comment by arbuz93** [comment]
Zadania przydzieliliśmy ci dopiero gdy omówiłem to z @Drego31 . Przyszedł niestety trochę późno i przez to tak wyszło…
@Erystyczny

**Comment by Erystyczny** [comment]
@arbuz93 luz, fb twitter co jeszcze? juz przestaje myslec :p

**Comment by arbuz93** [comment]
Póki co tylko te dwa. Jeżeli będą mieli więcej social media, to jutro się wszystkiego dopytamy. Kurde, trzeba zrobić jakąś listę pytań xD.
@Erystyczny

**Comment by Erystyczny** [comment]
https://www.dropbox.com/sh/lf0xnauaqvth3qh/AADA02rDBrmTBzjjK6-cPH7na?dl=0
@arbuz93 
_b - bez tła

**Comment by arbuz93** [comment]
Zrób jeszcze wypełnione na biało w środku i te x64 :smile:.
@Erystyczny

**Comment by Erystyczny** [comment]
_w - z białym,64 po co wam na teraz

**Comment by arbuz93** [comment]
x64 można zrobić później.
@Erystyczny

**Comment by arbuz93** [comment]
Z portali społecznościowych potrzebujemy tylko FB, więc zamykam. Najwyżej później będzie zmiana czegoś w tym logo FB, jeżeli zajdzie taka potrzeba.
@Erystyczny
