### ISSUE TITLE
Zmiana czcionki dla logo i motto strony.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#25]
### Na życzenie klienta, mamy zmienić czcionkę na bardziej standardową.

Nie podoba im się taka podłużna, w sensie, tak bardzo wyższa niż szersza. Ma być mniej więcej taka, jak na okładce od ich katalogu z produktami **Deltaplus**. @Drego31 ma ten katalog w formie PDF do pobrania z internetu poprzez aplikację na pendriverze. Podobno jest to aplikacja, która waży 60 MB i jest przeznaczona dla windowsa (tzn. '*.exe'). Nie wiem kto pisał tą aplikację, ale chyba nie wiedział jak to się robi...

**Comment by Drego31** [comment]
#### Poniżej są ikonki zagrożeń i zawodów
Przydało by się je wyciąć i wydzielić każdą w osobnym pliku ;)
@Erystyczny 

![screenshot_20160622_123612](https://cloud.githubusercontent.com/assets/6503362/16263822/96cc77fc-3876-11e6-9f06-60727ca12060.png)

![screenshot_20160622_123552](https://cloud.githubusercontent.com/assets/6503362/16263768/555c01de-3876-11e6-986e-a07c939cb592.png)

**Comment by Erystyczny** [comment]
### Tło i czcionki mott'a

https://www.dropbox.com/sh/v4fe689nwgg1t57/AACmkpIfjbtLKbGWUqMn4jila?dl=0

**Comment by Erystyczny** [comment]
### odzież robocza i ikona FB - #ff7000

https://www.dropbox.com/sh/jhllw3rbhsv2b0m/AABsuadZdVxRBwpFyyBcRJ_2a?dl=0
@Drego31

**Comment by dbetka** [comment]
### O to efekty:

![screenshot_20160628_170424](https://cloud.githubusercontent.com/assets/6503362/16420638/659faa56-3d52-11e6-9211-24624221e6ca.png)

@Erystyczny @arbuz93

**Comment by Erystyczny** [comment]
nie chciałbyś motta przesunąć bardziej na lewo na tą ścianę?? troche mnie kują w oczy te półki pod nim

**Comment by dbetka** [comment]
Jasne, zobaczę jutro @Erystyczny

**Comment by arbuz93** [comment]
Dobra. Logo i motto jest zrobione. Tapeta się nie podoba klientom, więc trzeba zmienić, ale to już inny issues. Zamykam
