### ISSUE TITLE
Zmiany w stopce.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#27]
### Stopka jest goła i raczej nie za wesoła. Zróbmy coś z tym.

Padła propozycja, żeby w stopce znalazły się następujące rzeczy:
- Udostępnianie katalogów z produktami do pobrania
- Lista linków tj niżej:  ![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-10_00-40-46.png)  
- Producenci, z którymi nasz klient ma deal.

Tyle mam tu zapisane. Myślę, że można tam jeszcze dodać coś z FB, no i coś @Drego31 mówił o jakże ważnym i koniecznym komunikatem o wykorzystywaniu cookies.

**Comment by dbetka** [comment]
@arbuz93 Wcześniej był już utworzony wątek

Wcześniejszy wątek zamykam
