### ISSUE TITLE
Potrzebujemy motto!

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#3]
#### Kolejne zadanie to:

Trzeba wykonać grafikę motta. Czcionka ma być taka jak w logo chyba, że znajdziesz tą budowlaną tak jak rozmawialiśmy.
Poniżej aktualny stan ↓

![screenshot_20160528_182544](https://cloud.githubusercontent.com/assets/6503362/15628457/1f60ca74-2502-11e6-8508-39969f7e5662.png)
#### Napis musi być widoczny na tym tle

![screenshot_20160528_183255](https://cloud.githubusercontent.com/assets/6503362/15628475/a0043102-2502-11e6-8f5f-696390b4170f.png)

**Comment by Erystyczny** [comment]
#### v0.1

lekko przeźroczyste ale nie do końca mam na to pomysł, jak macie jakieś sugestie to jestem otwarty
![motto v0 1](https://cloud.githubusercontent.com/assets/19621505/15629353/3e2f8c6e-2517-11e6-9a3a-1c4e5cf803df.png)

**Comment by dbetka** [comment]
@Erystyczny Chodzi Ci, że na takim tle lekko przeźroczystym?

@arbuz93 Masz pomysł?

**Comment by arbuz93** [comment]
Myślę, że motto może mieć jakieś tło, ale powinno ono gładko przechodzić na zdjęcie pod spodem w sposób nie rażący odbiorcę. Czcionka chyba dobrze się komponuje ze stroną jak i logiem. @Drego31 @Erystyczny

**Comment by Erystyczny** [comment]
### Podlgląd:

![motto v1 1](https://cloud.githubusercontent.com/assets/19621505/15683113/0e0ec5da-2761-11e6-8379-c907f174d383.png)

sama warstwa
https://www.dropbox.com/s/0ldwjjfqlpov7wa/motto%20v1.1%20t%C5%82o.png?dl=0

**Comment by dbetka** [comment]
Sam pomysł jest spoko! ;)
Jednak czemu taki kolor? :O @Erystyczny 
[ASBHP - aktualna strona](http://asbhp.pl/) o taką kolorystykę mamy się opierać

**Comment by Erystyczny** [comment]
jako że interesuje sie filmmakingem to czerpie z tego wiele wiedzy i to jeden z tych momentów a wiec wyjasnienie:

![basic-color-theory-for-filmmakers-4-638](https://cloud.githubusercontent.com/assets/19621505/15690114/4d3cedd8-2782-11e6-8e62-bdbcfb2ac7a8.jpg)

@Drego31

**Comment by dbetka** [comment]
Rozumiem, tylko obawiam się, że klientowi może się to nie spodobać bo to nie pasuje do reszty strony.
Wszędzie są kolory w pewnej gamie a tu nagle błękit O.o
Trzeba by albo ustalić wspólne kolory albo wziąć inny wg mnie

**Comment by Erystyczny** [comment]
To mogę zrobić takie samo tylko szare, co myślisz?

**Comment by arbuz93** [comment]
@Drego31 ma teraz znowu matury, bo w terminach się nie zmieścił. Myślę, że tło mogłoby być ciemniejsze od tej chmury na której się znajduje. Ale nie wiem czy warto w ogóle teraz się tym zajmować, bo właśnie dostaliśmy materiały od ziomeczków. Są tam zdjęcia wszystkich produktów (oczywiście w PDF, bo jak by inaczej xD) i jakieś tapety, które może wykorzystamy na stronę startową. Wtedy do tych nowych zdjęć dopasujemy wygląd napisu. W sensie kolor pod nim. Napis spoko :smiley: . 

Niedługo pójdziemy na kolejne spotkanie z mistrzami BHP i pochwalimy się, co udało nam się do tej pory sklepać, uzgodnimy kolory itd. 
@Erystyczny

**Comment by dbetka** [comment]
Moje zdanie jest takie, że najlepiej jak będzie szare ale we wtorek tego typu sprawy dokładnie omówimy.
Na razie wykonaj z szarym, półprzeźroczystym tłem tak by dobrze komponowało się ze stroną ;)
@Erystyczny

**Comment by Erystyczny** [comment]
Mam to i 3 rodzaje czcionek w sumie to są te same ale lekko zmienione. Pod tym wrzucam jeszcze jedno zdjecie bo jakoś mi ten dymek nie podchodzi i mysle o innych mozliwosciach.
![motto v1 2](https://cloud.githubusercontent.com/assets/19621505/15872939/616d25d2-2cfc-11e6-9422-03ddc351c073.jpg)

Nie wiem czy patrzeliście ale mają Facebooka ASBHP wiec może coś w tym stylu?
![propozycja_2](https://cloud.githubusercontent.com/assets/19621505/15872959/87df50b4-2cfc-11e6-80e0-f91bcfe836dd.jpg)

**Comment by dbetka** [comment]
@Erystyczny Myślę, że jak wybierzemy zdjęcie jutro to wtedy dopasujemy motto

**Comment by dbetka** [comment]
Prześlij mi oba motta @Erystyczny

**Comment by Erystyczny** [comment]
https://www.dropbox.com/sh/tg9yv99wv9ulaim/AAAeFIjbfpiJ12TtkPGIRA1ia?dl=0
