### ISSUE TITLE
Problem z linkami JS na całej stronie internetowej.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#32]
### W Firefox nie działa przechodzenie między zakładkami - problem z linkami.

Komunikat o błędzie wygląda w ten sposób:
![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-12_02-10-01.png)  
- Problem w tym, że Firefox inaczej obsługuje mysz. Tutaj jest przykładowe rozwiązanie problemu, które znalazłem na stackoverflow: 
  ![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-12_02-12-57.png)  
- Tu masz cały temat: http://stackoverflow.com/questions/7051112/using-event-which-to-verify-if-the-user-pressed-the-spacebar-doesnt-work-in-fir

**Comment by dbetka** [comment]
Już @arbuz93
