### ISSUE TITLE
Ikonki zagrożeń i zawodów

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#37]
#### Poniżej są ikonki zagrożeń i zawodów

Przydało by się je wyciąć i wydzielić każdą w osobnym pliku ;)
@Erystyczny 

![screenshot_20160622_123612](https://cloud.githubusercontent.com/assets/6503362/16263822/96cc77fc-3876-11e6-9f06-60727ca12060.png)

![screenshot_20160622_123552](https://cloud.githubusercontent.com/assets/6503362/16263768/555c01de-3876-11e6-986e-a07c939cb592.png)

**Comment by dbetka** [comment]
Tutaj też masz katalog, z którego zrobiłem screeny

[http://publication.deltaplus.eu/cat-2015-pl/](http://publication.deltaplus.eu/cat-2015-pl/)

**Comment by Erystyczny** [comment]
Mają być przezroczyste?

**Comment by dbetka** [comment]
Na około tak, w środku obrazki nie

**Comment by Erystyczny** [comment]
### Wszystkie piktogramy 32x32

https://www.dropbox.com/sh/f8l081hkv6amapl/AADqIfMNI9l5kXwE37wVJA_za?dl=0

**Comment by Erystyczny** [comment]
### 64x64 aktualne

https://www.dropbox.com/sh/f8l081hkv6amapl/AADqIfMNI9l5kXwE37wVJA_za?dl=0
