### ISSUE TITLE
Dynamiczne formularze dla dodawania nowego produktu.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#39]
### Dla zwiększenie wygody - przede wszystkim naszej, bo to my będziemy te produkty wpisywać - dodawanie nowego produktu powinno posiadać w kilku miejscach dynamiczne formularze, których zadaniem będzie uzupełniać tabele (słowniki) w bazie danych.

Powinno to dotyczyć takich słowników jak: 
- Producent produktu 
- Kolor produktu
- Certyfikaty 

Estetyka należy do ciebie. Miło byłoby, gdyby strona nie musiała przeładowywać się za każdym dodanym rekordem do słownika, bo będzie wymazywało wcześniej wpisane dane w formularzu. Skoro bieżemy się za dodawanie rekordów do słowników, to od razu wrzućmy tam opcje usunięcia.

**Comment by arbuz93** [comment]
Myślę, że całkiem ciekawym pomysłem może być dodanie osobnych formularzy do edycji tych słowników na stronie dodawania produktu. Takie niezależne formularze, które będą dynamicznie wysyłały i uzupełniały formularz główny (dodawania produktu).

**Comment by dbetka** [comment]
Odpuszczamy to sobie do kolejnego projektu @arbuz93
