### ISSUE TITLE
Ikonka menu dla urządzeń mobilnych

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#41]
#### Tutaj jest aktualna

![menu](https://cloud.githubusercontent.com/assets/6503362/16418307/81a869f8-3d49-11e6-8f65-0dc0f9dac834.png)
#### Jak ma wyglądać?

Najlepiej jak będzie pomarańczowa z przeźroczystym tłem.
Nie wiem czy to obramowanie jest potrzebne - może wystarczą tylko te 3 kreski, więc zrób oba.

**Comment by Erystyczny** [comment]
jaka rodziałka? taka jak to co wstawiłeś? najlepiej pisz od razu jakiej wielkosci mają być rzeczy które mam zrobić chyba że nie ma konkretnych wytycznych.
@Drego31

**Comment by dbetka** [comment]
32x32 Ok będę pisał @Erystyczny

**Comment by Erystyczny** [comment]
### ikonka z obramowaniem i bez:

https://www.dropbox.com/s/j5lh8dxwp25gajv/menu_64.png?dl=0

**Comment by dbetka** [comment]
#### Dzięki @Erystyczny → Twoja ikonka w akcji :P

![screenshot_20160629_003941](https://cloud.githubusercontent.com/assets/6503362/16434771/0476143c-3d92-11e6-9782-96b6a1313162.png)
