### ISSUE TITLE
Ikonka fb jest zła :/

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#42]
### Trzeba usunąć tło w środku ikonki fb

Średnio to wygląda:

![screenshot_20160628_160919](https://cloud.githubusercontent.com/assets/6503362/16418568/b7862686-3d4a-11e6-877c-54fdc0709000.png)

**Comment by Erystyczny** [comment]
https://www.dropbox.com/s/kry9bczi9aav3ls/FB%20P.png?dl=0
@Drego31

**Comment by dbetka** [comment]
Jest git

![screenshot_20160628_170303](https://cloud.githubusercontent.com/assets/6503362/16420603/32e8cf7a-3d52-11e6-88b6-cfb7dc58bcf4.png)
