### ISSUE TITLE
Początkowa wartość dla ilości wyświetlanych produktów

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#46]
![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-07-05_01-39-33.png)

**Comment by dbetka** [comment]
Błąd jest po mojej czy Twojej stronie?
@arbuz93

**Comment by arbuz93** [comment]
Po obu stronach, i dlatego zaznaczyłem nas obu. Ja muszę stworzyć zmienną, która będzie zawierała odpowiednią wartość tego selecta, a ty będziesz musiał ustawić te wartość w tym selecie jakoś. Może jest możliwość ustawienia na starcie po mojej stronie. Muszę zobaczyć. @Drego31

**Comment by dbetka** [comment]
To stwórz zmienną a ja pokombinuje @arbuz93

**Comment by arbuz93** [comment]
Sam sobie poradziłem. Zamykam.
