### ISSUE TITLE
Błąd podczas wyświetlania szczegółów produktu

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#50]
![](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-07-06_00-25-27.png)

**Comment by dbetka** [comment]
Nie potrafię powtórzyć tych błędów
@arbuz93

**Comment by arbuz93** [comment]
Ja dałem radę to powtórzyć. Wejdź na stronę http://asbhp.arbuz.team/oferta/ i wtyszukaj ten produkt po nazwie. Następnie spróbuj wyświetlić szczegóły tego produktu (click na niego). @Drego31 
![](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-07-19_19-28-45.png)

**Comment by dbetka** [comment]
To przez błędny typ danych wczytywanych do funkcji `html` przy wpisywaniu danych do html
