### ISSUE TITLE
Linki do katalogów

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#57]
### Trzeba zrobić adresy url dla katalogów produktów do pobrania w postaci PDF.

Moja propozycja, to umieszczenie ich w zakładce O_Firmie. To raczej twoja robota jest, ale jak będziesz miał jakiś problem, to pisz.

Producentów, od których mamy wziąć produkty i katalogi jest jednak szcześciu. Lepiej mniej niż więcej, więc pomyliłem się w dobrą stronę xD.

**Katalogi:**  
- http://www.industrialstarter.com/pl/katalogi 
- http://publication.deltaplus.eu/cat-2015-pl/ 
- http://www.portwest.eu/footer_data.php?do=7 
- https://www.adler.info/PL/pl/Article/katalog-90/ 
- http://www.filter-service.eu/pl/index.php (nie mogę znaleźć katalogu) 
- http://protekt.com.pl/?page=kategoria_tekst&kat=&menu_id=6

**Comment by dbetka** [comment]
@arbuz93 Tutaj wstępny efekt:

![screenshot_20160724_232704](https://cloud.githubusercontent.com/assets/6503362/17086572/4d7f2416-51f6-11e6-965f-1541ea0583fa.png)

**Comment by arbuz93** [comment]
Spoko. Myślę, że będzie git. Przydałoby się tylko zamiast linków dać jakieś obrazki jak w producentach, albo chociażby oryginalne nazwy producentów. @Drego31

**Comment by dbetka** [comment]
To może nazwa myślnik i link. Powtarzać dwa razy obrazki wg mnie nie ma sensu @arbuz93

**Comment by arbuz93** [comment]
Ok, ale w formie spisu treści. Tzn. podziel to na 2 kolumny z przesunięciem tekstu do lewej, gdzie w pierwszej będą nazy, a w drugiej linki. @Drego31
