### ISSUE TITLE
Kontakt - dodatkowe pola

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#68]
Trzeba dodać dodatkowe pola (tak jak wcześniejsze) dla godzin otwarcia

**Comment by arbuz93** [comment]
- Zmienna zawierająca formularz edycji godzin otwarcia - godziny 
- Adres do zapisu danych formularza - /zapisz/godziny/ 
- Zmienna zawierająca zawartość godzin otwarcia dla zakładki 'Kontakt' - godziny
