### ISSUE TITLE
Przygotowanie ikonki do paska przeglądarki

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#7]
#### Co zrobić?

Wykonaj ikonkę do paska przeglądarki - wizja dowolna.

Moja propozycja to: ↓↓↓↓↓ xD

![untitled](https://cloud.githubusercontent.com/assets/6503362/15658856/06dbb5e2-26c2-11e6-9946-bd18a9d5d6d8.png)

**Comment by Erystyczny** [comment]
| ![ic b_w](https://cloud.githubusercontent.com/assets/19621505/15683383/59ca108c-2762-11e6-8e58-c641d9897f10.jpg) | ![ic w_b](https://cloud.githubusercontent.com/assets/19621505/15683387/5db20dd0-2762-11e6-973d-fe1bd56023a7.jpg) |
| --- | --- |

Wer 1 - https://www.dropbox.com/s/38ty00vdjwpop8n/ic%20b_w.jpg?dl=0
Wer 2 - https://www.dropbox.com/s/1lsalm3tbimjitb/ic%20w_b.jpg?dl=0

**Comment by dbetka** [comment]
Co o tym sądzicie? @Erystyczny @arbuz93 

![screenshot_20160607_025506](https://cloud.githubusercontent.com/assets/6503362/15842648/49f9a50c-2c5b-11e6-9081-a95e2971d177.png)

![screenshot_20160607_025310](https://cloud.githubusercontent.com/assets/6503362/15842647/49f9205a-2c5b-11e6-9e5a-bc4b095fcc6a.png)

**Comment by arbuz93** [comment]
Wydaje mi się, że mogło być bardziej kolorowo. Dlaczego nie zrobić pomarańczowego A na przeźroczystym lub białym tle. Nawet na białym tle takie pomarańczowe A wyglądało by już super.
W końcu takie mają logo, to może się tego trzymajmy :eyes:.
@Drego31 @Erystyczny

**Comment by Erystyczny** [comment]
![as_black](https://cloud.githubusercontent.com/assets/19621505/15870481/baf3df30-2cf0-11e6-800a-e4e7ada99247.png)

> https://www.dropbox.com/s/jlbdebg2vxlhad5/AS_Black.png?dl=0

![as_white](https://cloud.githubusercontent.com/assets/19621505/15870509/cac62792-2cf0-11e6-8686-691b5a1fa10d.png)

> https://www.dropbox.com/s/gw7xan5kr5e083w/AS_White.png?dl=0

**Comment by dbetka** [comment]
Zrób jeszcze z przeźroczystym tłem bym mógł sprawdzić jak i to wygląda @Erystyczny

**Comment by Erystyczny** [comment]
https://www.dropbox.com/s/axqsmqmqug6486r/AS.PNG?dl=0

**Comment by dbetka** [comment]
#### @Erystyczny Najlepsze jest bez tła!

Tylko trzeba jedną rzecz zrobić.
Musisz powiększyć napis i zmniejszyć odstępy między napisem a krawędzią grafiki a to dlatego 
↓↓↓↓↓↓

![screenshot_20160608_005223](https://cloud.githubusercontent.com/assets/6503362/15877457/2d05c1f6-2d14-11e6-89d0-b4059fb2458a.png)

**Comment by Erystyczny** [comment]
https://www.dropbox.com/s/2ksjye7vjkpogd5/AS2.png?dl=0

**Comment by dbetka** [comment]
O to efekt:

![screenshot_20160609_002311](https://cloud.githubusercontent.com/assets/6503362/15913105/64c45598-2dd8-11e6-894c-6ad0a466de9c.png)

Zamykam @Erystyczny
