### ISSUE TITLE
Tytuły stron są wszystkie takie same

### ISSUE THREAD

**Issue by dbetka** [arbuz-team/asbhp#70]
### Tutaj  -  ↓↓↓

![screenshot_20160801_000826](https://cloud.githubusercontent.com/assets/6503362/17279716/16681b14-577c-11e6-9e7b-fc30e53fd709.png)

**Comment by dbetka** [comment]
@arbuz93  
Tytuły to np. `As BHP - Odzież robocza` - startowa
`O firmie - As BHP` - o firmie itd

**Comment by arbuz93** [comment]
Nazwa zmiennej - tytul_strony.
Znajduje się w zakładkach: Start, O_Firmie, Oferta, Kontakt.
@Drego31
