### ISSUE TITLE
Problem z CSS na stronie startowej.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#8]
Podczas wyświetlania ID zawodów i zagrożeń, wszystkie <div> nachodzą na siebie tworząc takie oto combo:
![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-01_00-53-17.png)

**Comment by dbetka** [comment]
Problemu już nie ma ale czekam na zdjęcia zagrożeń i zawodów.
