### ISSUE TITLE
Wyświetlanie produktów.

### ISSUE THREAD

**Issue by arbuz93** [arbuz-team/asbhp#9]
Trzeba napisać wyświetlanie produktów przedzielonych zakładkami: typ, dziedzina, rodzaj - odzieży. Wstępnie ustalam zarys tej podstrony:
![dropbox](https://dl.dropboxusercontent.com/u/8297754/screenshots/Przechwycenie%20obrazu%20ekranu_2016-06-04_01-53-21.png)

**Comment by arbuz93** [comment]
Rysowałem to online na stronie:
https://mudcu.be/sketchpad/
Jeżeli macie lepsze, łatwo dostępne oprogramowanie do sporządzania takich szkiców, możecie tu napisać, żeby wszystkim było łatwiej. @Drego31 @Erystyczny

**Comment by Erystyczny** [comment]
@arbuz93
https://www.rollapp.com/launch/gimp
Wybierasz test drive i możesz korzystać z pełnych możliwości gimpa, co ciekawe sprawdziłem i działa nawet na telefonie ;D

**Comment by arbuz93** [comment]
O super! To będę sobie z tego korzystał :smiley:.

**Comment by dbetka** [comment]
Oferta już jest wstępnie zrobiona wraz z filtrami. 
@arbuz93 @Erystyczny 

![screenshot_20160607_024403](https://cloud.githubusercontent.com/assets/6503362/15842490/c9a69604-2c59-11e6-8787-19bf2f86ae79.png)
